AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0.0
  Exclude:
    - bin/**/*
    - db/**/*
    - bundle_bin/**/*
  Include:
    - dwca_hunter.gemspec
    - exe/dwcahunter

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - "*.gemspec"
    - "**/*.rake"
    - "spec/**/*spec.rb"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
